"""Unit tests for TrackFlow RAG retrieval and generation pipeline."""

from __future__ import annotations

from unittest.mock import MagicMock, patch
import pytest

from data.pipelines.rag import (
    NO_CONTEXT_MESSAGE,
    generate_answer,
    query,
    retrieve,
)


class DummyPoint:
    """Simulated Qdrant point result."""

    def __init__(self, point_id: str, score: float, payload: dict):
        self.id = point_id
        self.score = score
        self.payload = payload


class DummyQueryResult:
    """Simulated Qdrant query_points response."""

    def __init__(self, points: list[DummyPoint]):
        self.points = points


class TestRetrieve:
    """Unit tests for retrieve() with simulated Qdrant client (no live DB in CI)."""

    def test_retrieve_filters_below_min_score(self):
        """Verifies that points with similarity score below min_score are strictly excluded."""
        mock_client = MagicMock()
        mock_points = [
            DummyPoint("p1", 0.85, {"source_document": "sla-delivery", "text": "SLA 90%"}),
            DummyPoint("p2", 0.60, {"source_document": "returns-policy", "text": "Ventana 30 días"}),
            DummyPoint("p3", 0.25, {"source_document": "carrier-coverage", "text": "Irrelevant chunk"}),
        ]
        mock_client.query_points.return_value = DummyQueryResult(mock_points)

        results = retrieve(
            query="¿Cuál es el SLA y ventana?",
            k=5,
            min_score=0.50,
            client=mock_client,
        )

        assert len(results) == 2
        assert results[0]["source_document"] == "sla-delivery"
        assert results[1]["source_document"] == "returns-policy"
        # The third point with score 0.25 must be excluded
        assert all(r["_score"] >= 0.50 for r in results)

    def test_retrieve_can_return_fewer_than_k(self):
        """Verifies that retrieve() returns fewer than k results when few chunks qualify."""
        mock_client = MagicMock()
        mock_points = [
            DummyPoint("p1", 0.92, {"source_document": "storage-pricing", "text": "Tarifa 18 USD"}),
        ]
        mock_client.query_points.return_value = DummyQueryResult(mock_points)

        results = retrieve(
            query="tarifas de almacenamiento",
            k=5,
            min_score=0.35,
            client=mock_client,
        )

        assert len(results) == 1
        assert results[0]["source_document"] == "storage-pricing"

    def test_retrieve_returns_empty_when_no_points_qualify(self):
        """Verifies that retrieve() returns an empty list if no points exceed min_score."""
        mock_client = MagicMock()
        mock_points = [
            DummyPoint("p1", 0.15, {"source_document": "carrier-coverage", "text": "Baja similitud"}),
            DummyPoint("p2", 0.10, {"source_document": "returns-policy", "text": "Muy baja similitud"}),
        ]
        mock_client.query_points.return_value = DummyQueryResult(mock_points)

        results = retrieve(
            query="receta de cocina",
            k=5,
            min_score=0.40,
            client=mock_client,
        )

        assert results == []

    def test_retrieve_returns_clean_payload_dicts(self):
        """Verifies that retrieve() returns dictionaries and not raw SDK objects."""
        mock_client = MagicMock()
        mock_points = [
            DummyPoint(
                "p1",
                0.88,
                {
                    "company": "trackflow",
                    "source_document": "carrier-coverage",
                    "section": "España (Zaragoza)",
                    "language": "es",
                    "chunk_index": 1,
                    "text": "SEUR cubre zonas rurales de Aragón.",
                },
            )
        ]
        mock_client.query_points.return_value = DummyQueryResult(mock_points)

        results = retrieve(
            query="cobertura aragón",
            k=3,
            min_score=0.50,
            client=mock_client,
        )

        assert len(results) == 1
        payload = results[0]
        assert isinstance(payload, dict)
        assert not hasattr(payload, "points")
        assert payload["company"] == "trackflow"
        assert payload["source_document"] == "carrier-coverage"
        assert "SEUR" in payload["text"]


class TestQuery:
    """Unit tests for query() and generate_answer() mocking retrieve and LLM."""

    @patch("data.pipelines.rag.retrieve")
    def test_query_returns_model_output(self, mock_retrieve):
        """Verifies that query() returns the output generated by the LLM."""
        mock_retrieve.return_value = [
            {
                "source_document": "sla-delivery",
                "section": "SLA de Entrega",
                "text": "El SLA es 90% a tiempo.",
            }
        ]

        mock_llm_client = MagicMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "Como account manager de TrackFlow, confirmo que nuestro SLA es del 90%."
        mock_response = MagicMock()
        mock_response.choices = [mock_choice]
        mock_llm_client.chat.completions.create.return_value = mock_response

        answer = query(
            question="¿Cuál es el SLA comprometido?",
            llm_client=mock_llm_client,
        )

        assert answer == "Como account manager de TrackFlow, confirmo que nuestro SLA es del 90%."
        mock_llm_client.chat.completions.create.assert_called_once()

    @patch("data.pipelines.rag.retrieve")
    def test_query_does_not_return_raw_chunk(self, mock_retrieve):
        """Verifies that query() does not return raw chunk text without generation."""
        raw_text = "Texto crudo directo de la base de datos sin formato ni saludo ni redacción comercial."
        mock_retrieve.return_value = [
            {
                "source_document": "returns-policy",
                "section": "Devoluciones",
                "text": raw_text,
            }
        ]

        mock_llm_client = MagicMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "Respuesta consultiva adaptada: En TrackFlow gestionamos las devoluciones de manera ágil."
        mock_response = MagicMock()
        mock_response.choices = [mock_choice]
        mock_llm_client.chat.completions.create.return_value = mock_response

        answer = query(
            question="¿Cómo funcionan las devoluciones?",
            llm_client=mock_llm_client,
        )

        assert answer != raw_text
        assert "Respuesta consultiva adaptada" in answer

    @patch("data.pipelines.rag.retrieve")
    def test_query_handles_empty_retrieval_honestly(self, mock_retrieve):
        """Verifies that query() admits lack of info when retrieve() returns no qualifying chunks."""
        mock_retrieve.return_value = []

        answer = query(question="¿Cuál es el menú del almuerzo en Zaragoza?")

        assert answer == NO_CONTEXT_MESSAGE
        assert "no contiene información suficiente" in answer.lower()

    def test_generate_answer_isolated_call(self):
        """Verifies generate_answer can be invoked directly as an isolated step."""
        context = [
            {
                "source_document": "carrier-coverage",
                "section": "España (Zaragoza)",
                "text": "SEUR tiene la mejor cobertura en zonas rurales de Aragón.",
            }
        ]

        mock_llm = MagicMock()
        mock_choice = MagicMock()
        mock_choice.message.content = "SEUR es el transportista ideal para zonas rurales en Aragón."
        mock_llm.chat.completions.create.return_value = MagicMock(choices=[mock_choice])

        result = generate_answer(
            question="¿Qué carrier cubre Aragón rural?",
            context=context,
            client=mock_llm,
        )

        assert "SEUR" in result
